### ISSUE TITLE
New line handling should be more forgiving

### ISSUE THREAD

**Issue by rubycon** [robmisasi/eslint-plugin-headers#2]
I currently work on a project with a mix of Unix and Windows line ending files. The header template I inject in my source file is in Unix style but some of the source files themselves are Windows style. Some code editor on our team normalize all line endings on save and git normalize them on commit. So during development on local environment line ending might often be inconsistent between files.

This prevent `eslint-plugin-headers` to correctly detect the header pattern already injected in some files because the line endings are different from the header template. Could the matching algorithm of the plugin be more forgiving of line ending ?

**Comment by rubycon** [comment]
@robmisasi Thanks.

IMO you don't have to detect the files current line ending. Let the user, the editor or git work that out.

But line endings type should be ignored or normalized for comparison during the linting process to avoid false negative.

**Comment by robmisasi** [comment]
@rubycon I apologize for the delay, I've published a new version of the plugin addressing this. Please let me know if you experience further issues.

**Comment by rubycon** [comment]
@robmisasi I also apologize for the delay, I was AFK for a month.

The new line agnostic matching works fine here. Thank you very much !
