### ISSUE TITLE
Detecting header

### ISSUE THREAD

**Issue by luiguild** [robmisasi/eslint-plugin-headers#3]
Hello, I'm trying to use your lib in a Vue Single File component, it works very well, thank you for the effort to create this.

However I'm facing an issue, after to apply the header, eslint keep giving me the error, even with the header there.

Examples:
No header, showing the error to be fixed
![image](https://github.com/robmisasi/eslint-plugin-headers/assets/16566338/3c2d443c-0b80-4080-9005-340f8cb4dc37)

After to run the --fix, works, the header is there
![image](https://github.com/robmisasi/eslint-plugin-headers/assets/16566338/51fceaf7-04a8-4c92-a0ea-0d69231cb651)

![image](https://github.com/robmisasi/eslint-plugin-headers/assets/16566338/2f869a03-53e1-4617-ba5e-7878973bdda2)

If I keep running --fix, the header continues to be added sequentially.

Do you have any idea about it?

Ps: Nothing special to be reproduced, just a clean vue3 project, typescript and eslint. All the other rules are working well.

**Comment by robmisasi** [comment]
Interesting, I hadn't experienced this behavior. Thank you for pointing out this issue, I will work to reproduce this and find a solution.

**Comment by robmisasi** [comment]
The reason this happens is because the plugin will look for a comment block at the beginning of the file, and then insert the missing comment before the first JS AST node. The JS AST no longer starts at the beginning of the file so this check will always fail.

**Comment by luiguild** [comment]
I see, so in other words, it's because is a Vue Single File component and the JS is only inside the tag `<script>`  so is impossible to put the header in the very first line of the file, right?

**Comment by robmisasi** [comment]
Right, the AST content exposed by ESlint will only include valid JS nodes. I would like to continue searching for a solution that could handle non-JS files consistently with JS files, but it will take some time to properly support additional languages. I've introduced a new version of this plugin that fixes the issue you've described (where the plugin produces an error even after the fix is applied), but this still inserts the comment with respect to the JS being linted.

**Comment by luiguild** [comment]
Yeah, at least the process to fix it's working, now is important to understand how the code knows where is the right place to put the header but doesn't know where to search to check if the header is already there.

**Comment by robmisasi** [comment]
I spent some time today trying to find parsers for Vue which could produce an AST that would let this plugin detect and parse header comments, but I wasn't able to find any that would support this. Unfortunately, the most popular and well documented Vue parser I could find,[vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser/tree/master), does not support comment nodes. I would prefer to avoid adding logic to perform this work in this project, so I'm not sure when I will be able to better support Vue SFC files. I will mark this issue as closed but am certainly open to enhancing support for Vue. 

Feel free to follow up if you have any ideas or experience further issues.
